name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Download Debian torrent
        run: curl -o input/debian.torrent https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/debian-12.5.0-amd64-netinst.iso.torrent

      - name: Build and run app
        run: make debian-test

      - name: Check output
        run: |
          if [ -f "output/debian.iso" ]; then
            echo "Output file exists."
          else
            echo "Output file not found."
            exit 1
          fi
      - name: Display logs
        run: cat logs/*.log
